# Generated by Django 4.2.2 on 2023-07-02 18:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='author_image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='author/image/'),
            preserve_default=False,
        ),
    ]
