# Generated by Django 4.2.2 on 2023-07-01 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_blog_categories_alter_blog_options_blog_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='description',
            new_name='short_description',
        ),
    ]
