# Generated by Django 4.2.2 on 2023-07-06 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_resource_author_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='resource_comment',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='resource_comment',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
