# Generated by Django 4.2.2 on 2023-07-02 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_alter_service_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='slug',
        ),
    ]
