# Generated by Django 4.2.2 on 2023-07-06 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_subscription_alter_resource_comment_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource_comment',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.resource'),
        ),
    ]
