# Generated by Django 4.2.2 on 2023-07-06 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_alter_resource_comment_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
