# Generated by Django 4.2.2 on 2023-07-01 12:43

from django.db import migrations
import django.utils.timezone
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0006_project_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=stdimage.models.StdImageField(default=django.utils.timezone.now, force_min_size=False, upload_to='project/image/', variations={}),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Project_Image',
        ),
    ]
