# Generated by Django 4.2.2 on 2023-07-17 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0006_blog_subscription_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='subscription_status',
            field=models.BooleanField(default=False),
        ),
    ]
