# Generated by Django 4.2.2 on 2023-07-17 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0007_resource_subscription_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='resource',
            name='author_image',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='resource',
            name='image',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.URLField(),
        ),
    ]
