# Generated by Django 4.2.2 on 2023-07-02 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0009_resource_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='short_description',
            field=models.CharField(max_length=200),
        ),
    ]
