# Generated by Django 4.2.2 on 2023-07-01 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0009_alter_project_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='image',
        ),
    ]
