# Generated by Django 4.2.2 on 2023-07-02 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0010_alter_resource_short_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='author_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
