# Generated by Django 4.2.2 on 2023-07-01 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0011_project_image1_project_image2_project_image3'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='short_description',
        ),
    ]
