# Generated by Django 4.2.2 on 2023-07-01 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0013_remove_blog_type_blog_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='slug',
            field=models.SlugField(blank=True, max_length=300, unique=True),
        ),
    ]
