# Generated by Django 4.2.2 on 2023-07-01 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0016_comment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comment',
            new_name='Blog_Comment',
        ),
    ]
