# Generated by Django 4.2.2 on 2023-07-01 16:09

from django.db import migrations, models
import faicon.fields
import froala_editor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0018_resource'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', faicon.fields.FAIconField(max_length=50)),
                ('title', models.CharField(max_length=50)),
                ('short_description', models.CharField(max_length=300)),
                ('content', froala_editor.fields.FroalaField()),
            ],
        ),
    ]
