# Generated by Django 4.2.2 on 2023-07-01 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0019_service'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='icon',
        ),
    ]
