# Generated by Django 4.2.2 on 2023-07-01 16:56

from django.db import migrations, models
import django.utils.timezone
import fontawesome_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0020_remove_service_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='icon',
            field=fontawesome_5.fields.IconField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='service',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='', verbose_name='company/service/'),
            preserve_default=False,
        ),
    ]
