# Generated by Django 4.2.2 on 2023-07-01 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0021_service_icon_service_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.ImageField(upload_to='company/service/'),
        ),
    ]
