# Generated by Django 4.2.2 on 2023-07-01 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0023_gallery_gallery_categories_delete_project_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='slug',
            field=models.SlugField(blank=True, max_length=300, unique=True),
        ),
    ]
