# Generated by Django 4.2.2 on 2023-07-01 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0026_gallery_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
