# Generated by Django 4.2.2 on 2023-07-01 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0027_alter_gallery_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallery',
            name='slug',
        ),
    ]
