# Generated by Django 4.2.2 on 2023-07-01 18:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0029_gallery_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='document_link',
            field=models.URLField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
