# Generated by Django 4.2.2 on 2023-07-01 18:39

from django.db import migrations
import fontawesome_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0030_resource_document_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='icon',
            field=fontawesome_5.fields.IconField(blank=True, max_length=60),
        ),
    ]
